name: "Release"

on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        run: npm install -g @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: "Semantic Release"
        run: npx semantic-release@22
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
